### PR TITLE
Express enums better in Typescript

### PR DESCRIPTION
**Pull request by koros**

### CODE REVIEW

**Review by andrueastman — COMMENTED** [review]
👍🏼

**Review by baywet — COMMENTED** [review]
The result looks good.
The generation result is probably going to conflict with the work I've done in #984 and associated PR, we should probably wait for those to be merged, rebase and update the generation here.

**Comment by baywet** [comment]
@koros let's revert the changes for generation and generate again.

```shell
git reset HEAD~1
git checkout **/generatedCode/**
#generate the code
git add .
git commit
git push -f
```

**Comment by koros** [comment]
> @koros let's revert the changes for generation and generate again.
> 
> ```shell
> git reset HEAD~1
> git checkout **/generatedCode/**
> #generate the code
> git add .
> git commit
> git push -f
> ```

Done, waiting for the pipeline to pick the changes

**Review by baywet — DISMISSED** [review]
do you think it'd be worth aligning the httpmethod enum we have in abstractions?

**Review by baywet — APPROVED** [review]

**Pull request merged**
